language: go

go:
  - "1.10.x"
  - master

cache:
  directories:
    - _testdata

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install: true

notifications:
  email: false

addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.6

before_script:
  - cd _testdata && ./tables.py 500 && cd ..
  - GO_FILES=$(find . -type f -iname '*.go')
  - go get -u -t ./...

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v tags=ddebug -timeout=12h -short -race ./...
